from miniworld_test.policy_interaction.heuristic_policy_random import HeuristicPolicyRandom
from miniworld_test.policy_interaction.heuristic_policy_mfmb import HeuristicPolicyMFMB
from miniworld_test.policy_interaction.heuristic_policy_rotate import HeuristicPolicyRotate
from miniworld_test.policy_interaction.heuristic_policy_repeat import HeuristicPolicyRepeat
